"""uwagi

Revision ID: 29e8dbe318f7
Revises: b698fa198a49
Create Date: 2024-03-17 10:58:46.540007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29e8dbe318f7'
down_revision = 'b698fa198a49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sprawa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uwagi', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sprawa', schema=None) as batch_op:
        batch_op.drop_column('uwagi')

    # ### end Alembic commands ###
