[tool.poetry]
name = "spoldzielnie"
version = "0.1.0"
description = ""
authors = ["szalaj <mszalajski@gmail.com>"]
readme = "README.md"
packages = [{include="*", from="src"}]

[tool.poetry.dependencies]
python = ">=3.9"
geojson = "^3.1.0"
pandas = "^2.2.1"
odfpy = "^1.4.1"
zipp = "^3.19.2"
flask-sqlalchemy = "^3.1.1"
flask-migrate = "^4.0.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
