"""organizacja

Revision ID: 12297ca3361b
Revises: 5fc091f0814f
Create Date: 2024-05-05 16:11:41.975908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12297ca3361b'
down_revision = '5fc091f0814f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizacja',
    sa.Column('nr', sa.Integer(), nullable=False),
    sa.Column('data_dodania', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('spoldzielnia', sa.String(), nullable=False),
    sa.Column('data_powstania', sa.DateTime(), nullable=True),
    sa.Column('data_koniec', sa.DateTime(), nullable=True),
    sa.Column('nazwa', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('dzialalnosc', sa.String(), nullable=True),
    sa.Column('opis', sa.String(), nullable=True),
    sa.Column('miejscowosc', sa.String(), nullable=True),
    sa.Column('odnosniki', sa.String(), nullable=True),
    sa.Column('uwagi', sa.String(), nullable=True),
    sa.Column('szerokosc_geo', sa.String(), nullable=True),
    sa.Column('dlugosc_geo', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['spoldzielnia'], ['spoldzielnia.krs'], ),
    sa.PrimaryKeyConstraint('nr')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organizacja')
    # ### end Alembic commands ###
