"""typ

Revision ID: 4f81e6a5d83b
Revises: 12297ca3361b
Create Date: 2024-08-06 21:37:25.697745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f81e6a5d83b'
down_revision = '12297ca3361b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sprawa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('typ', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sprawa', schema=None) as batch_op:
        batch_op.drop_column('typ')

    # ### end Alembic commands ###
