"""a1

Revision ID: 5fc091f0814f
Revises: c49f8724f201
Create Date: 2024-04-08 22:09:36.216157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fc091f0814f'
down_revision = 'c49f8724f201'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spoldzielnia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dzielnica', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spoldzielnia', schema=None) as batch_op:
        batch_op.drop_column('dzielnica')

    # ### end Alembic commands ###
