"""zysk uchwala

Revision ID: 6177a977eb96
Revises: 29e8dbe318f7
Create Date: 2024-04-01 11:26:56.980965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6177a977eb96'
down_revision = '29e8dbe318f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('walne',
    sa.Column('nr', sa.Integer(), nullable=False),
    sa.Column('data_dodania', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('spoldzielnia', sa.String(), nullable=False),
    sa.Column('bylo', sa.Boolean(), nullable=True),
    sa.Column('kiedy_bylo', sa.DateTime(), nullable=True),
    sa.Column('rok_kalendarzowy', sa.String(), nullable=True),
    sa.Column('bilans', sa.Float(), nullable=True),
    sa.Column('zysk_netto', sa.Float(), nullable=True),
    sa.Column('glosowanie_za', sa.Integer(), nullable=True),
    sa.Column('glosowanie_przeciw', sa.Integer(), nullable=True),
    sa.Column('glosowanie_wstrzymujacy', sa.Integer(), nullable=True),
    sa.Column('glosowanie_niewazne', sa.Integer(), nullable=True),
    sa.Column('uchwala', sa.String(), nullable=True),
    sa.Column('uwagi', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['spoldzielnia'], ['spoldzielnia.krs'], ),
    sa.PrimaryKeyConstraint('nr')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('walne')
    # ### end Alembic commands ###
