"""zgloszenie

Revision ID: b698fa198a49
Revises: 8ebcbd2ff56e
Create Date: 2024-03-17 10:58:06.985399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b698fa198a49'
down_revision = '8ebcbd2ff56e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sprawa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('zgloszenie', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('kontakt', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sprawa', schema=None) as batch_op:
        batch_op.drop_column('kontakt')
        batch_op.drop_column('zgloszenie')

    # ### end Alembic commands ###
