"""walne

Revision ID: c49f8724f201
Revises: 6177a977eb96
Create Date: 2024-04-06 10:52:17.408756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c49f8724f201'
down_revision = '6177a977eb96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('walne', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sprawozdanie_finansowe', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('uchwala_zatw', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('w_sprawie', sa.String(), nullable=True))
        batch_op.drop_column('rok_kalendarzowy')
        batch_op.drop_column('zysk_netto')
        batch_op.drop_column('uchwala')
        batch_op.drop_column('bylo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('walne', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bylo', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('uchwala', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('zysk_netto', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('rok_kalendarzowy', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('w_sprawie')
        batch_op.drop_column('uchwala_zatw')
        batch_op.drop_column('sprawozdanie_finansowe')

    # ### end Alembic commands ###
