"""data dodania

Revision ID: e852efa2a2d8
Revises: f3ecd14aed35
Create Date: 2024-03-17 10:47:06.267302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e852efa2a2d8'
down_revision = 'f3ecd14aed35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sprawa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_dodania', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sprawa', schema=None) as batch_op:
        batch_op.drop_column('data_dodania')

    # ### end Alembic commands ###
