"""init

Revision ID: f0cb75459ac6
Revises: 
Create Date: 2024-03-09 11:50:42.567489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0cb75459ac6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spoldzielnia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nazwa', sa.String(), nullable=True),
    sa.Column('krs', sa.String(), nullable=True),
    sa.Column('nip', sa.String(), nullable=True),
    sa.Column('regon', sa.String(), nullable=True),
    sa.Column('adres', sa.String(), nullable=True),
    sa.Column('kod_pocztowy', sa.String(), nullable=True),
    sa.Column('miejscowosc', sa.String(), nullable=True),
    sa.Column('forma_prawna', sa.String(), nullable=True),
    sa.Column('data_rejestracji', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('szerokosc_geo', sa.String(), nullable=True),
    sa.Column('dlugosc_geo', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spoldzielnia')
    # ### end Alembic commands ###
