"""dodanie Spraw

Revision ID: f3ecd14aed35
Revises: f0cb75459ac6
Create Date: 2024-03-17 10:43:48.800070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3ecd14aed35'
down_revision = 'f0cb75459ac6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sprawa',
    sa.Column('nr', sa.Integer(), nullable=False),
    sa.Column('spoldzielnia', sa.String(), nullable=False),
    sa.Column('data_rozpoczenia', sa.DateTime(), nullable=True),
    sa.Column('data_zakonczenia', sa.DateTime(), nullable=True),
    sa.Column('opis', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('kategoria', sa.String(), nullable=True),
    sa.Column('odnosniki', sa.String(), nullable=True),
    sa.Column('szerokosc_geo', sa.String(), nullable=True),
    sa.Column('dlugosc_geo', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['spoldzielnia'], ['spoldzielnia.krs'], ),
    sa.PrimaryKeyConstraint('nr')
    )
    with op.batch_alter_table('spoldzielnia', schema=None) as batch_op:
        batch_op.alter_column('krs',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spoldzielnia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))
        batch_op.alter_column('krs',
               existing_type=sa.VARCHAR(),
               nullable=True)

    op.drop_table('sprawa')
    # ### end Alembic commands ###
